Repository jonhue/notifications-rails, pull requests merged in 2018-07, with the labels that each got.

#6 [#5] Add issue templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: enhancement

#13 [#14] Calling default_category on NotificationRenderer.configuration
  notification-settings/lib/notification_settings/notification_library.rb
Labels: bug, good first issue

#16 [#15] render_notifications not working
  notification-renderer/app/helpers/notification_renderer_helper.rb
Labels: bug

#20 [#9] Update pull request template
  PULL_REQUEST_TEMPLATE.md
Labels: enhancement

#19 [#10] Update contribution guidelines
  CONTRIBUTING.md
Labels: enhancement

#18 [#11] Update code of conduct
  CODE_OF_CONDUCT.md
Labels: enhancement

#21 [#8] Update README.md
  README.md
  notifications-rails.gemspec
Labels: enhancement

#23 [#22] Fix link to GitHub project in Readme
  README.md
Labels: bug

#25 [#24] Remove License from Table of Contents (Readme)
  README.md
Labels: enhancement
